<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

use Tilta\Payment\Block\Widget\Telephone;
use Tilta\Payment\ViewModel\CustomerAccount\FacilityForm;

$viewModel = $block->getData('view_model');
if (!$viewModel instanceof FacilityForm) {
    throw new \Exception('invalid view model in ' . $block->getTemplate());
}

$buyerData = $viewModel->getAddress()->getExtensionAttributes()?->getTiltaBuyer();
?>
<fieldset class="fieldset">
    <?= $block->getChildHtml() ?>

    <div class="field choice">
        <input type="checkbox" id="toc" name="toc" value="1" class="checkbox" required>
        <label class="label" for="toc">
            <span><?= /** @noEscape */ $viewModel->getToc() ?></span>
        </label>
    </div>
</fieldset>
