<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<p class="tilta-facility-intro"><?= __('You can apply for a credit limit to use Invoice Payments. After you are approved, you will have a site-wide credit limit, allowing you to delay payment for the orders that fit into your limit. Requesting a credit limit from us does not affect your credit rating.') ?></p>
