name: Code Analyse

on:
    push:
        branches:
            - dev
            - task/*
    pull_request:

env:
    EXTENSION_DIR: _git/extension/
    COMPOSER_NAME: tilta/magento-2-payment-module

jobs:
    default:
        name: Lint (Magento ${{ matrix.magento-version }}, PHP ${{ matrix.php-version }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                magento-version:
                    - 2.4.6
                    - 2.4.7
                php-version:
                    - 8.1
                    - 8.2
                    - 8.3

                exclude:
                    -   magento-version: 2.4.6
                        php-version: 83
                    -   magento-version: 2.4.7
                        php-version: 81
            fail-fast: false
            max-parallel: 10

        steps:
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
                    extensions: dom, curl, libxml, mbstring, zip, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
                    coverage: none

            -   name: Create Magento project
                run: |
                    composer create-project --repository-url=https://repo-magento-mirror.fooman.co.nz/ magento/project-community-edition:^${{ matrix.magento-version }} . --no-install
                    composer config --unset repositories.0
                    composer config repositories.fooman-mirror composer https://repo-magento-mirror.fooman.co.nz/

            -   name: "Get composer cache directory"
                id: composer-cache
                run: echo "dir=$(composer config cache-files-dir -d)" >> $GITHUB_OUTPUT

            -   name: "Cache Composer dependencies"
                uses: actions/cache@v3
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ matrix.php-version }}-${{ matrix.magento-version }}-${{ hashFiles('**/composer.json') }}

            -   name: Install magento dependencies
                # install with no-dev to prevent conflicts with dev-tools
                run: composer install --no-dev

            -   name: Checkout code
                uses: actions/checkout@v2
                with:
                    path: ${{ env.EXTENSION_DIR }}

            -   name: "Install ${{ env.COMPOSER_NAME }}"
                run: |
                    composer config prefer-stable true
                    composer config minimum-stability dev
                    composer config repositories.local '{ "type": "path", "url": "_git/*", "options": { "symlink": true } }'
                    composer req ${{ env.COMPOSER_NAME }} --no-scripts --no-plugins

            -   name: "Install DEV-Tools"
                working-directory: ${{ env.EXTENSION_DIR }}
                run: |
                    composer remove magento/* --no-update
                    composer install

            -   name: "Run PHPStan"
                working-directory: ${{ env.EXTENSION_DIR }}
                run: ./vendor/bin/phpstan analyse --autoload-file ../../vendor/autoload.php

            -   name: "Check Code style (rector)"
                working-directory: ${{ env.EXTENSION_DIR }}
                run: ./vendor/bin/rector process --dry-run --autoload-file ../../vendor/autoload.php

            -   name: "Check Code style (easy-coding-style)"
                working-directory: ${{ env.EXTENSION_DIR }}
                run: ./vendor/bin/ecs check
